#!/bin/bash
# build_mac_app.sh — assemble, sign, and install AkioStudio.app.
#
# Implements the audited packaging design (ARCHITECTURE_AUDIT.md):
#   B4  Info.plist carries ONLY real keys — there is no Metal/MPS "permission".
#   B5  Build into ./dist/AkioStudio.app, never directly into /Applications.
#   B6  Generated launcher exports an explicit PATH (Dock apps get a bare one).
#   A7  Ad-hoc codesign is the FINAL build step; the bundle is never modified after.
#   A8  venv/logs live under ~/Library/Application Support/AkioStudio, outside the
#       signed bundle.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIST="$SCRIPT_DIR/dist"
APP="$DIST/AkioStudio.app"
CONTENTS="$APP/Contents"
ICON_MASTER="$SCRIPT_DIR/resources/icon/AkioStudio_1024.png"
MODE="install"
LINT_ONLY=0

usage() {
  cat <<'USAGE'
Usage: build_mac_app.sh [--build-only | --install] [--icon <1024px-png>] [--lint]

  (no flags)     Build dist/AkioStudio.app, ad-hoc sign it, then install it.
  --build-only   Build + sign only; skip the install step.
  --install      Build + sign + install (explicit form of the default).
  --icon PATH    1024x1024 PNG icon master (default: resources/icon/AkioStudio_1024.png).
  --lint         Linux/CI-safe: bash -n the generated launcher, validate the
                 generated Info.plist, print the build plan, and exit. No build.
  -h, --help     Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --build-only) MODE="build-only"; shift ;;
    --install) MODE="install"; shift ;;
    --icon) [ "$#" -ge 2 ] || { echo "error: --icon requires a path" >&2; exit 1; }
            ICON_MASTER="$2"; shift 2 ;;
    --lint) LINT_ONLY=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown flag: $1" >&2; usage >&2; exit 1 ;;
  esac
done

# Launcher generated into Contents/MacOS/. Quoted heredoc: nothing expands at
# build time — every $VAR below is resolved at *launch* time on the user's Mac.
launcher_content() {
  cat <<'LAUNCHER'
#!/bin/bash
# AkioStudioLauncher — generated by build_mac_app.sh. Do not edit in place:
# the bundle is code-signed and any edit invalidates the signature (audit A7).
set -euo pipefail

# 1. Resolve bundle-relative paths — never rely on cwd (Dock gives none useful).
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
RESOURCES="$APP_DIR/Resources"

# 2. Dock/Finder apps inherit a minimal PATH without Homebrew (audit B6).
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

# 3. Mutable state lives OUTSIDE the signed bundle (audit A8).
SUPPORT="$HOME/Library/Application Support/AkioStudio"
VENV="$SUPPORT/venv"
LOGS="$SUPPORT/logs"
mkdir -p "$VENV" "$LOGS"

# First launch: bootstrap the orchestrator venv (stdlib + networkx only —
# torch/ComfyUI/Ollama run in their own processes, audit B3/M1).
if [ ! -x "$VENV/bin/python" ]; then
  /usr/bin/env python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet -r "$RESOURCES/requirements.txt"
fi

# 4. Audited runtime environment: one resident model, one request lane (A1);
# flash attention + q8_0 KV cache to shrink the context budget (A3).
export OLLAMA_MAX_LOADED_MODELS=1
export OLLAMA_NUM_PARALLEL=1
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_KV_CACHE_TYPE=q8_0
# CPU-fallback escape hatch for unimplemented MPS ops — NOT an "MPS enabler".
export PYTORCH_ENABLE_MPS_FALLBACK=1
AKIO_OLLAMA_BIN="$(command -v ollama || echo /opt/homebrew/bin/ollama)"
export AKIO_OLLAMA_BIN

# 5. Hand this process over to the orchestrator dashboard.
exec "$VENV/bin/python" "$RESOURCES/main.py" --dashboard \
  >> "$LOGS/akio-studio.log" 2>&1
LAUNCHER
}

# Real keys only (audit B4): no invented Metal/MPS "permission" keys exist.
info_plist_content() {
  cat <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>com.akiostudio.app</string>
  <key>CFBundleName</key><string>Akio Studio</string>
  <key>CFBundleDisplayName</key><string>Akio Studio</string>
  <key>CFBundleExecutable</key><string>AkioStudioLauncher</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleIconFile</key><string>AkioStudio</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSApplicationCategoryType</key><string>public.app-category.graphics-design</string>
</dict>
</plist>
PLIST
}

if [ "$LINT_ONLY" -eq 1 ]; then
  TMP_LAUNCHER="$(mktemp)"
  launcher_content > "$TMP_LAUNCHER"
  bash -n "$TMP_LAUNCHER" && echo "lint: generated launcher parses (bash -n OK)"
  rm -f "$TMP_LAUNCHER"
  info_plist_content | /usr/bin/env python3 -c \
    'import plistlib,sys; plistlib.loads(sys.stdin.buffer.read()); print("lint: generated Info.plist parses (plistlib OK)")'
  cat <<PLAN
Build plan (executed on Darwin only):
  1. Assemble $APP (Contents/{MacOS,Resources})
  2. Copy payload -> Contents/Resources/: akio_studio/, main.py, requirements.txt
  3. Write Contents/Info.plist (real keys only, audit B4); plutil -lint
  4. Icon: sips 16..512(+@2x) + iconutil from $ICON_MASTER (skip if absent)
  5. Write Contents/MacOS/AkioStudioLauncher (chmod +x)
  6. codesign --force --deep --sign - (LAST build step, audit A7)
  7. Install mode '$MODE': ditto -> /Applications (fallback ~/Applications),
     then lsregister -f + touch
PLAN
  exit 0
fi

if [ "$(uname -s)" != "Darwin" ]; then
  echo "error: building AkioStudio.app requires macOS (sips/iconutil/plutil/codesign)." >&2
  echo "       On other platforms use --lint to validate the generated content." >&2
  exit 1
fi

for payload in "$SCRIPT_DIR/akio_studio" "$SCRIPT_DIR/main.py" "$SCRIPT_DIR/requirements.txt"; do
  [ -e "$payload" ] || { echo "error: missing payload: $payload" >&2; exit 1; }
done

echo "==> Assembling bundle skeleton in $APP (audit B5: never build in /Applications)"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

echo "==> Copying payload into Contents/Resources/"
ditto "$SCRIPT_DIR/akio_studio" "$CONTENTS/Resources/akio_studio"
find "$CONTENTS/Resources/akio_studio" -type d -name "__pycache__" -exec rm -rf {} +
cp "$SCRIPT_DIR/main.py" "$SCRIPT_DIR/requirements.txt" "$CONTENTS/Resources/"

echo "==> Writing Contents/Info.plist"
info_plist_content > "$CONTENTS/Info.plist"
plutil -lint "$CONTENTS/Info.plist"

if [ -f "$ICON_MASTER" ]; then
  echo "==> Generating AkioStudio.icns from $ICON_MASTER"
  ICONSET="$DIST/AkioStudio.iconset"
  rm -rf "$ICONSET"; mkdir -p "$ICONSET"
  for size in 16 32 128 256 512; do
    sips -z "$size" "$size" "$ICON_MASTER" \
      --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
    sips -z "$((size * 2))" "$((size * 2))" "$ICON_MASTER" \
      --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$CONTENTS/Resources/AkioStudio.icns"
  rm -rf "$ICONSET"
else
  echo "warning: no icon master at $ICON_MASTER — skipping .icns (pass --icon <png>)" >&2
fi

echo "==> Writing Contents/MacOS/AkioStudioLauncher"
launcher_content > "$CONTENTS/MacOS/AkioStudioLauncher"
chmod +x "$CONTENTS/MacOS/AkioStudioLauncher"
bash -n "$CONTENTS/MacOS/AkioStudioLauncher"

echo "==> Ad-hoc signing (audit A7: LAST step — the bundle is immutable from here)"
codesign --force --deep --sign - "$APP"
echo "==> Built $APP"

if [ "$MODE" = "build-only" ]; then
  echo "==> --build-only: skipping install."
  exit 0
fi

if [ -w /Applications ]; then
  TARGET="/Applications/AkioStudio.app"
else
  echo "==> /Applications not writable; falling back to ~/Applications"
  mkdir -p "$HOME/Applications"
  TARGET="$HOME/Applications/AkioStudio.app"
fi
echo "==> Installing to $TARGET"
rm -rf "$TARGET"
ditto "$APP" "$TARGET"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
"$LSREGISTER" -f "$TARGET" || echo "warning: lsregister re-registration failed" >&2
touch "$TARGET"
echo "==> Installed $TARGET (LaunchServices/Spotlight re-registered)"
